# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Lowe CI Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # Setup Job
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run start
    - run: |
          npm test
          npm run coverage
          MIN_COVERAGE=80  # substitua pela porcentagem mínima desejada
          CURRENT_COVERAGE=$(npx istanbul check-coverage --lines $MIN_COVERAGE)
          if [ "$CURRENT_COVERAGE" == "false" ]; then
            echo "A cobertura de código não atinge a porcentagem mínima necessária."
            exit 1
          fi
